dist: trusty
os: linux
language: node_js
node_js:
- node
- '9'
addons:
  chrome: stable
  firefox: latest

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &